server:
  port: 80
spring:
  application:
    name: SpringCloud-consumer-80-spring-application


# eureka消费者配置
eureka:
  client:
    register-with-eureka: false # 不向eureka注册自己
    service-url:
      defaultZone: http://www.eureka7002.com:7001/eureka/,http://www.eureka7002.com:7002/eureka/,http://www.eureka7003.com:7003/eureka/
